volumes:
  vw-data:
    external: true
  vw-data-a:
    external: true

services:
  accounts_service:
    
    build:
      context: accounts_service
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./accounts_service:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SIGNING_KEY: ${SIGNING_KEY}

  monolith_service:
    build:
      context: monolith_service
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8000
    volumes:
      - ./monolith_service:/app
    environment:
      S3_BUCKET: ${S3_BUCKET}
      REGION: ${REGION}
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
      DATABASE_URL: ${DATABASE_URL}
      SIGNING_KEY: ${SIGNING_KEY}

  db:
    build:
      context: data
      dockerfile: Dockerfile.dev
    volumes:
      - vw-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: VW
      POSTGRES_USER: VW
      POSTGRES_DB: farm
    ports:
      - "15432:5432"

  db-a:
    build:
      context: data_a
      dockerfile: Dockerfile.dev
    volumes:
      - vw-data-a:/var/lib/postgresql/data_a/
    environment:
      POSTGRES_PASSWORD: VW
      POSTGRES_USER: VW
      POSTGRES_DB: accounts
    ports:
      - "15400:5432"

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_API_HOST: http://localhost:8000
      REACT_APP_API_HOST_MONOLITH: http://localhost:8080
      REACT_APP_REACT_HOST: http://localhost:3000
      
    
  # pg-admin:
  #   image: dpage/pgadmin4
  #   volumes:
  #     - pg-admin:/var/lib/pgadmin
  #   ports:
  #     - 8082:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: me@me.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #     PGADMIN_DISABLE_POSTFIX: 1
  