volumes:
  vw-data:
    external: true
services:
  fastapi:
    build:
      context: sample_service
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./sample_service:/app
  monolith_service:
    build:
      context: monolith_service
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8000
    volumes:
      - ./monolith_service:/app
  db:
    build:
      context: data
      dockerfile: Dockerfile.dev
    volumes:
      - vw-data:/var/lib/postgresql/data
    ports:
      - "8100:8000"
  
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_API_HOST: http://localhost:8000

            