volumes:
  vw-data:
    external: true
services:
  fastapi:
    build:
      context: sample_service
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./sample_service:/app
  monolith_service:
    build:
      context: monolith_service
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8000
    volumes:
      - ./monolith_service:/app
    environment:
      DATABASE_URL: postgresql://monolith:monolith@db/monolith
  db:
    build:
      context: data
      dockerfile: Dockerfile.dev
    volumes:
      - vw-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: VW
      POSTGRES_USER: VW
      POSTGRES_DB: farm
    ports:
      - "15432:5432"
  # pg-admin:
  #   image: dpage/pgadmin4
  #   volumes:
  #     - pg-admin:/var/lib/pgadmin
  #   ports:
  #     - 8082:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: me@me.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #     PGADMIN_DISABLE_POSTFIX: 1
  
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_API_HOST: http://localhost:8000/

            